#!/usr/bin/env sh

TUTORIALS_DIR=docs/source/tutorials

# For each *qmd file in model/docs, create a corresponding rst file
# under docs/source/tutorial
for qmd in model/docs/*.qmd; do
    # Capture the basename
    bname=$(basename $qmd .qmd)

    # Check if the corresponding rst file already exists
    if [ -f ${TUTORIALS_DIR}${bname}.rst ]; then
        echo "RST file already exists: ${TUTORIALS_DIR}${bname}.rst"
        continue
    fi

    # Create the rst file
    rst=${TUTORIALS_DIR}/${bname}.rst
    echo "Creating $rst"

    # Print a message pointing to github.com/CDCgov/ on the rst file
    echo ".. WARNING" > $rst
    echo ".. Please do not edit this file directly." >> $rst
    echo ".. This file is just a placeholder." >> $rst
    echo ".. For the source file, see:" >> $rst
    echo ".. <https://github.com/CDCgov/multisignal-epi-inference/tree/main/model/docs/${bname}.qmd>" >> $rst

done
