site_name: "PyRenew"
repo_url: "https://github.com/CDCgov/PyRenew"

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tooltips
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - offline
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: "brief"
            docstring_style: "numpy"
            scoped_crossrefs: true
            # not yet available in free public release
            line_length: 80
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            merge_init_into_class: true

          paths: ["."]
          inventories:
            - url: "https://docs.python.org/3/objects.inv"
            - url: "https://docs.pola.rs/api/python/stable/objects.inv"
              # but see https://github.com/pola-rs/polars/issues/7027
            - url: "https://numpy.org/doc/stable/objects.inv"
            - url: "https://python.arviz.org/en/stable/objects.inv"
      enable_inventory: true
