[tool.poetry]
name = "multisignal-epi-inference"
version = "0.1.0"
description = "Python package for statistical inference and forecast of epi models using multiple signals."
authors = ["CFA"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "multisignal_epi_inference"}]

[tool.poetry.dependencies]
python = "^3.12"
numpyro = "^0.15.1"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
numpydoc = "^1.7.0"

[tool.numpydoc_validation]
checks = [
    "GL03",
    "GL08",
    "SS01",
    "PR03",
    "PR04",
    "PR07",
    "RT01"
]
ignore = [
    "ES01",
    "SA01",
    "EX01",
    "SS06",
    "RT05"
]
exclude = [  # don't report on objects that match any of these regex
    '\.undocumented_method$',
    '\.__repr__$',
    '\.__call__$'
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
