---
title: Fitting an hospitalizations only model
format: gfm
engine: jupyter
---

This document illustrates how a hospitalization-only model can be fitted using data from the Pyrenew package, particularly the wastewater dataset. The CFA wastewater team created this dataset, which contains simulated data.

```{python}
#| label: setup
import polars as pl
from pyrenew.datasets import load_wastewater
from pyrenew.model import HospitalizationsModel
```

## Model definition

In this section we provide the formal definition of the model. The hospitalization model is a semi-mechanistic model that describes the number of observed hospitalizations as a function of a set of latent variables. Particularly, the observed number of hospitalizations is discretily distributed with location at the number of latent hospitalizations:

$$
h(t) \sim \text{HospDist}\left(H(t)\right)
$$

Where $h(t)$ is the observed number of hospitalizations at time $t$, and $H(t)$ is the number of latent hospitalizations at time $t$. The distribution $\text{HospDist}$ can be any discrete distribution, but in this case we will use a negative binomial distribution.

The number of latent hospitalizations at time $t$ is a function of the number of latent infections at time $t$ and the infection to hospitalization rate. The latent infections are modeled as a renewal process:

$$
I(t) = R(t) \times \sum_{\tau < t} I(\tau) g(t - \tau)
$$

The reproductive number $R(t)$ is modeled as a random walk process:

$$
\begin{align*}
R(t) & = R(t-1) + \epsilon\\
\log{\epsilon} & \sim \text{Normal}(0, \sigma) \\
R(0) &\sim \text{TruncatedNormal}(\text{loc}=1.2, \text{scale}=0.2, \text{min}=0)
\end{align*}
$$



## Data processing

We start by loading the data and inspecting the first five rows.

```{python}
#| label: data-inspect
dat = load_wastewater()
dat.head(5)
```

The data shows one entry per site. We will take the aggregated data for all sites by date.

```{python}
#| label: aggregation
dat = dat.group_by("date").agg(
    hospitalizations = pl.sum("daily_hosp_admits"),
    population = pl.sum("pop"),
)

# Now, sorting by date
dat = dat.sort("date")

# Keeping the first 90 days
dat = dat.head(90)

dat.head(5)
```

Let's take a look at the daily prevalence of hospitalizations.

```{python}
#| label: plot-hospitalizations
import matplotlib.pyplot as plt

# Rotating the x-axis labels, and only showing ~10 labels
ax = plt.gca()
ax.xaxis.set_major_locator(plt.MaxNLocator(nbins=10))
ax.xaxis.set_tick_params(rotation=45)
plt.plot(dat["date"].to_numpy(), dat["hospitalizations"].to_numpy())
plt.xlabel("Date")
plt.ylabel("Hospitalizations")
plt.show()
```

## Building the model

First, we will extract two datasets that we will use as deterministic quantities, the generation interval and the infection to hospitalization interval.

```{python}
#| label: data-extract
from pyrenew.datasets import (
    load_generation_interval,
    load_infection_admission_interval,
)

gen_int = load_generation_interval()
inf_hosp_int = load_infection_admission_interval()

# We only need the probability_mass column of each dataset
gen_int = gen_int["probability_mass"].to_numpy()
inf_hosp_int = inf_hosp_int["probability_mass"].to_numpy()

# Taking a pick at the first 5 elements of each
gen_int[:5], inf_hosp_int[:5]

# Visualizing both quantities side by side
fig, axs = plt.subplots(1, 2)

axs[0].plot(gen_int)
axs[0].set_title("Generation interval")
axs[1].plot(inf_hosp_int)
axs[1].set_title("Infection to hospitalization interval")
```

With these two in hand, we can start building the model. First, we will define the latent hospitalizations.

```{python}
#| label: latent-hosp
from pyrenew.latent import HospitalAdmissions, InfectHospRate
from pyrenew.deterministic import DeterministicPMF
import jax.numpy as jnp
import numpyro.distributions as dist

inf_hosp_int = DeterministicPMF(inf_hosp_int)

hosp_rate = InfectHospRate(
    dist=dist.LogNormal(jnp.log(0.05), 0.05)
)

latent_hosp = HospitalAdmissions(
    infection_to_admission_interval=inf_hosp_int,
    infect_hosp_rate_dist=hosp_rate,
    )
```

Now we can define the rest of the other model components:

```{python}
#| label: initializing-rest-of-model
from pyrenew.model import HospitalizationsModel
from pyrenew.latent import Infections, Infections0
from pyrenew.process import RtRandomWalkProcess
from pyrenew.observation import NegativeBinomialObservation

# Infection process
latent_inf = Infections()
I0 = Infections0()

# Generation interval and Rt
gen_int = DeterministicPMF(gen_int)
process = RtRandomWalkProcess()

# The observation model
obs = NegativeBinomialObservation(concentration_prior=1.0)
```

Notice all the components are `RandomVariable` instances. We can now build the model:

```{python}
#| label: init-model
model = HospitalizationsModel(
    latent_infections=latent_inf,
    latent_hospitalizations=latent_hosp,
    I0=I0,
    gen_int=gen_int,
    Rt_process=process,
    observed_hospitalizations=obs,
)
```

Let's run a simulation to check if the model is working:

```{python}
#| label: simulation
import numpyro as npro
import numpy as np

timeframe = 120

np.random.seed(223)
with npro.handlers.seed(rng_seed = np.random.randint(1, timeframe)):
    sim_data = model.sample(n_timepoints=timeframe)
```

```{python}
#| label: basic-fig
#| fig-cap: Rt and Infections
#| fig-cap-location: bottom
import matplotlib.pyplot as plt

fig, axs = plt.subplots(1, 2)

# Rt plot
axs[0].plot(range(0, timeframe + 1), sim_data[0])
axs[0].set_ylabel('Rt')

# Infections plot
axs[1].plot(range(0, timeframe + 1), sim_data[1])
axs[1].set_ylabel('Infections')

fig.suptitle('Basic renewal model')
fig.supxlabel('Time')
plt.tight_layout()
plt.show()
```

## Fitting the model

Now we can fit the model to the data. We will use the `run` method of the model object. The two inputs this model requires are `n_timepoints` and `observed_hospitalizations`


```{python}
#| label: model-fit
import jax

model.run(
    num_samples=2000,
    num_warmup=1000,
    n_timepoints=dat.shape[0] - 1,
    observed_hospitalizations=dat["hospitalizations"].to_numpy(),
    rng_key=jax.random.PRNGKey(54),
    mcmc_args=dict(progress_bar=False),
)
```


```{python}
#| label: output-hospitalizations
#| fig-cap: Hospitalizations posterior distribution
#| fig-cap-location: bottom
import polars as pl
samps = model.spread_draws([('predicted_hospitalizations', 'time')])

fig, ax = plt.subplots(figsize=[4, 5])

ax.plot(dat["hospitalizations"].to_numpy(), color="black")
samp_ids = np.random.randint(size=25, low=0, high=999)
for samp_id in samp_ids:
    sub_samps = samps.filter(pl.col("draw") == samp_id).sort(pl.col('time'))
    ax.plot(sub_samps.select("time").to_numpy(),
            sub_samps.select("predicted_hospitalizations").to_numpy(), color="darkblue", alpha=0.1)

# Some labels
ax.set_xlabel("Time")
ax.set_ylabel("Hospitalizations")

# Adding a legend
ax.plot([], [], color="darkblue", alpha=0.9, label="Posterior samples")
ax.plot([], [], color="black", label="Observed hospitalizations")
ax.legend()
```
