#!/usr/bin/env sh

TUTORIALS_DIR=docs/source/tutorials

# For each *qmd file in docs/source/tutorials, create a corresponding rst file
# under docs/source/tutorials
COUNTER=0

# Removing everything under docs/source/tutorials/*rst with the exception of the index.rst file.
# This is to ensure that the index.rst file is not deleted.
RST_FILES=$(find $TUTORIALS_DIR -type f -name '*.rst' -not -name 'index.rst')

# Counting which of the rst files are not in model/docs
for rst in $RST_FILES; do
    # Capture the basename
    bname=$(basename $rst .rst)

    # Check if the corresponding qmd file exists
    if [ ! -f ${TUTORIALS_DIR}/${bname}.qmd ]; then
        echo "Removing $rst"
        rm $rst
    fi
done

for qmd in ${TUTORIALS_DIR}/*.qmd; do
    # Capture the basename
    bname=$(basename $qmd .qmd)

    # Check if the corresponding rst file already exists
    if [ -f ${TUTORIALS_DIR}/${bname}.rst ]; then
        continue
    fi

    # Increment counter
    COUNTER=$((COUNTER+1))

    # Create the rst file
    rst=${TUTORIALS_DIR}/${bname}.rst
    echo "Creating $rst"

    # Print a message pointing to github.com/CDCgov/ on the rst file
    echo ".. WARNING" > $rst
    echo ".. Please do not edit this file directly." >> $rst
    echo ".. This file is just a placeholder." >> $rst
    echo ".. For the source file, see:" >> $rst
    echo ".. <https://github.com/CDCgov/multisignal-epi-inference/tree/main/${TUTORIALS_DIR}/${bname}.qmd>" >> $rst

done

# Exit with 1 if COUNTER != 0
if [ $COUNTER -ne 0 ]; then
    echo "Tutorials' RST placeholders were generated."
    exit 1
fi
