name: Build container image

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Installs podman
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends podman

      - name: Log in to ghcr.io
        run: |
          podman login \
            -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/cdcgov

      - name: Build container image
        run: |
          make image-build
          podman tag pyrenew:latest ghcr.io/cdcgov/pyrenew:latest
          podman push ghcr.io/cdcgov/pyrenew:latest
        working-directory: model
