name: Build container image

on:
    workflow_dispatch:
    # These should be removed once the PR is merged. See
    # https://stackoverflow.com/questions/63362126/github-actions-how-can-i-run-a-workflow-created-on-a-non-master-branch-from-t
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Installs podman
              run: |
                sudo apt-get update
                sudo apt-get install -y --no-install-recommends podman

            - name: Build container image
              run: |
                make image-build
              working-directory: model
