name: Coverage

on:
  workflow_run:
    workflows: ["installation and testing model"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Retrieve artifacts (coverage from the CI)
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CDCgov/multisignal-epi-inference
