name: installation and testing pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: cache poetry
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: ${{ runner.os }}-poetry
      - name: install poetry
        run: pip install poetry
      - name: install package
        run: poetry install -C pipeline
      - name: run tests
        run: poetry run -C pipeline pytest pipeline
